language: node_js

node_js:
  - '8'
  - '10'
  - '12'
  - '14'
  - '15'

branches:
  only:
    - master
    - travis-ci

install:
  - npm install --no-package-lock --no-save
  - npm install -g nyc prove

script:
  - nyc npm test
